# site properties and page defaults
title: Pearce Lab
subtitle: Anesthetic mechanisms and memory
description: We are interested in how general anesthetics modulate memory formation through GABAA receptors. We utilize hippocampal brain slice electrophysiology, calcium imaging, confocal, and 2-photon microscopy
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: rapearce@wisc.edu
  orcid: 0000-0002-1516-6260
  google-scholar: https://scholar.google.com/citations?user=UsNzXC8AAAAJ&hl=en
  github: kbartol02

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
